exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex.raw('DELETE FROM "asana_sequence"; ALTER SEQUENCE asana_sequence_id_seq RESTART WITH 19;')
    .then(function () {
      var asana_sequences = [{
        id: 1,
        asanaID: 1,
        sequenceID: 1,
        sortOrder: 2
      }, {
        id: 2,
        asanaID: 2,
        sequenceID: 1,
        sortOrder: 3
      }, {
        id: 3,
        asanaID: 3,
        sequenceID: 1,
        sortOrder: 1
      }, {
        id: 4,
        asanaID: 4,
        sequenceID: 1,
        sortOrder: 4
      }, {
        id: 5,
        asanaID: 5,
        sequenceID: 1,
        sortOrder: 5
      }, {
        id: 6,
        asanaID: 6,
        sequenceID: 1,
        sortOrder: 6
      }, {
        id: 7,
        asanaID: 7,
        sequenceID: 1,
        sortOrder: 7
      }, {
        id: 8,
        asanaID: 8,
        sequenceID: 1,
        sortOrder: 8
      }, {
        id: 9,
        asanaID: 9,
        sequenceID: 1,
        sortOrder: 9
      }, {
        id: 10,
        asanaID: 1,
        sequenceID: 2,
        sortOrder: 1
      }, {
        id: 11,
        asanaID: 2,
        sequenceID: 2,
        sortOrder: 2
      }, {
        id: 12,
        asanaID: 3,
        sequenceID: 2,
        sortOrder: 3
      }, {
        id: 13,
        asanaID: 4,
        sequenceID: 2,
        sortOrder: 4
      }, {
        id: 14,
        asanaID: 5,
        sequenceID: 2,
        sortOrder: 5
      }, {
        id: 15,
        asanaID: 6,
        sequenceID: 2,
        sortOrder: 6
      }, {
        id: 16,
        asanaID: 7,
        sequenceID: 2,
        sortOrder: 7
      }, {
        id: 17,
        asanaID: 8,
        sequenceID: 2,
        sortOrder: 8
      }, {
        id: 18,
        asanaID: 9,
        sequenceID: 2,
        sortOrder: 9
      }, ];
      return knex('asana_sequence').insert(asana_sequences);
    });
};
