exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex.raw('DELETE FROM "asana_sequence"; ALTER SEQUENCE asana_sequence_id_seq RESTART WITH 19;')
    .then(function () {
      var asana_sequences = [{
        id: 1,
        asanaID: 1,
        sequenceID: 1,
        sortOrder: 2
      }, {
        id: 2,
        asanaID: 2,
        sequenceID: 1,
        sortOrder: 3
      }, {
        id: 3,
        asanaID: 3,
        sequenceID: 1,
        sortOrder: 1
      }, {
        id: 4,
        asanaID: 4,
        sequenceID: 1,
        sortOrder: 4
      }, {
        id: 5,
        asanaID: 5,
        sequenceID: 1,
        sortOrder: 5
      }, {
        id: 6,
        asanaID: 6,
        sequenceID: 1,
        sortOrder: 6
      }, {
        id: 7,
        asanaID: 7,
        sequenceID: 1,
        sortOrder: 7
      }, {
        id: 8,
        asanaID: 8,
        sequenceID: 1,
        sortOrder: 8
      }, {
        id: 9,
        asanaID: 9,
        sequenceID: 1,
        sortOrder: 9
      }, {
        id: 10,
        asanaID: 1,
        sequenceID: 2,
        sortOrder: 1
      }, {
        id: 11,
        asanaID: 2,
        sequenceID: 2,
        sortOrder: 2
      }, {
        id: 12,
        asanaID: 3,
        sequenceID: 2,
        sortOrder: 3
      }, {
        id: 13,
        asanaID: 4,
        sequenceID: 2,
        sortOrder: 4
      }, {
        id: 14,
        asanaID: 5,
        sequenceID: 2,
        sortOrder: 5
      }, {
        id: 15,
        asanaID: 6,
        sequenceID: 2,
        sortOrder: 6
      }, {
        id: 16,
        asanaID: 7,
        sequenceID: 2,
        sortOrder: 7
      }, {
        id: 17,
        asanaID: 8,
        sequenceID: 2,
        sortOrder: 8
      }, {
        id: 18,
        asanaID: 9,
        sequenceID: 2,
        sortOrder: 9
      }, {
        id: 19,
        asanaID: 5,
        sequenceID: 3,
        sortOrder: 1
      }, {
        id: 20,
        asanaID: 9,
        sequenceID: 3,
        sortOrder: 2
      }, {
        id: 21,
        asanaID: 10,
        sequenceID: 3,
        sortOrder: 3
      }, {
        id: 22,
        asanaID: 11,
        sequenceID: 3,
        sortOrder: 4
      }, {
        id: 23,
        asanaID: 12,
        sequenceID: 3,
        sortOrder: 5
      }, {
        id: 24,
        asanaID: 13,
        sequenceID: 3,
        sortOrder: 6
      }, {
        id: 25,
        asanaID: 1,
        sequenceID: 4,
        sortOrder: 1
      }, {
        id: 26,
        asanaID: 3,
        sequenceID: 4,
        sortOrder: 2
      }, {
        id: 27,
        asanaID: 5,
        sequenceID: 4,
        sortOrder: 3
      }, {
        id: 28,
        asanaID: 13,
        sequenceID: 4,
        sortOrder: 4
      }, {
        id: 29,
        asanaID: 14,
        sequenceID: 4,
        sortOrder: 5
      }, {
        id: 30,
        asanaID: 15,
        sequenceID: 4,
        sortOrder: 6
      },  {
        id: 31,
        asanaID: 1,
        sequenceID: 5,
        sortOrder: 1
      }, {
        id: 32,
        asanaID: 3,
        sequenceID: 5,
        sortOrder: 2
      }, {
        id: 33,
        asanaID: 7,
        sequenceID: 5,
        sortOrder: 3
      }, {
        id: 34,
        asanaID: 13,
        sequenceID: 5,
        sortOrder: 4
      }, {
        id: 35,
        asanaID: 12,
        sequenceID: 5,
        sortOrder: 5
      }, {
        id: 36,
        asanaID: 15,
        sequenceID: 5,
        sortOrder: 6
      }];
      return knex('asana_sequence').insert(asana_sequences);
    });
};
